version: "3"
services:
  postgres:
    container_name: task-service-task-manager-app-db
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: taskservice
      POSTGRES_USER: taskservice
      POSTGRES_PASSWORD: taskservice
    ports:
      - "65432:5432"
    networks:
      - task_manager_net
    volumes:
      - task-service-task-manager-app-db-data:/var/lib/postgresql/data
  task-service-task-manager-app:
    image: task-service-task-manager-app
    container_name: task-service-task-manager-app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
      - "5005:5005"
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=dev
    depends_on:
      - postgres
    networks:
      - task_manager_net
    restart: always
volumes:
  task-service-task-manager-app-db-data:
networks:
  task_manager_net:
    driver: bridge
